version: "3.1"

services:
  jenkins:
    build: ./jenkins
    image: jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    networks:
      - devops
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - /opt/tools-devops/Source/docker/build/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  artifactory:
    build: ./artifactory
    image: artifactory
    container_name: artifactory
    ports:
      - 8082:8082
    networks:
      - devops
    volumes:
     - /opt/tools-devops/Source/docker/build/artifactory:/var/opt/jfrog/artifactory
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

networks:
  devops:
    driver: bridge
